ALTER TABLE kb_knowledge_base
    COMMENT = '知识库基本信息表',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '知识库主键',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '知识库名称',
    MODIFY COLUMN description TEXT NULL COMMENT '知识库描述',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE kb_document
    COMMENT = '知识库文档元数据表',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '文档主键',
    MODIFY COLUMN knowledge_base_id BIGINT NOT NULL COMMENT '所属知识库ID',
    MODIFY COLUMN file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    MODIFY COLUMN file_type VARCHAR(128) NOT NULL COMMENT '文件类型',
    MODIFY COLUMN file_size BIGINT NOT NULL COMMENT '文件大小（字节）',
    MODIFY COLUMN storage_key VARCHAR(512) NOT NULL COMMENT '文件存储标识',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT '处理状态：PENDING待处理，INDEXING处理中，INDEXED处理完成，FAILED处理失败',
    MODIFY COLUMN chunk_count INT NOT NULL DEFAULT 0 COMMENT '文档分块数量',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';
